language: generic
sudo: required
services:
  - docker

before_install:
  # Force (-f) docker to build using Dockerfile.dev
  - docker build -t manjiltamang/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true manjiltamang/docker-react npm run test -- --coverage
