version: "3"
services:
  web:
    stdin_open: true
    build:
      context: . # Look for files in current directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

    #Override the initial command
    command: ["npm", "run", "test"]
